# Generated by Django 5.2.7 on 2026-02-27 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_migrate_batch_to_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbatch',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='productbatch',
            name='store',
        ),
    ]
