# Generated by Django 5.2.7 on 2026-03-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_productbatch_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('g', 'г'), ('pcs', 'шт')], default='pcs', max_length=10, verbose_name='Ед. изм.'),
        ),
    ]
