# Generated by Django 5.2.7 on 2026-03-01 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(verbose_name='Изменение (дельта)')),
                ('reason', models.CharField(choices=[('IN', 'Приход'), ('OUT', 'Списание'), ('RESERVE_GIFT', 'Резерв в подарок'), ('RETURN_GIFT', 'Возврат из подарка'), ('ADJUST', 'Корректировка')], max_length=20, verbose_name='Причина')),
                ('comment', models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Кто сделал')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='catalog.stock', verbose_name='Остаток (партия+магазин)')),
            ],
            options={
                'verbose_name': 'Движение остатка',
                'verbose_name_plural': 'Движения остатков',
                'ordering': ['-created_at'],
            },
        ),
    ]
