# Generated by Django 5.2.7 on 2026-03-02 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_stockmovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('IN', 'Корректировка (+'), ('OUT', 'Корректировка (-)'), ('RESERVE_GIFT', 'Резерв в подарок'), ('RETURN_GIFT', 'Возврат из подарка'), ('ADJUST', 'Корректировка')], max_length=20, verbose_name='Причина'),
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('ASSEMBLED', 'Собран'), ('SOLD', 'Продан'), ('CANCELED', 'Отменён/Разобран')], default='DRAFT', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gifts_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто собрал')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gifts', to='catalog.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Подарок',
                'verbose_name_plural': 'Подарки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Дополнительно (название)')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.gift', verbose_name='Подарок')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gift_items', to='catalog.stock', verbose_name='Со склада')),
            ],
            options={
                'verbose_name': 'Позиция подарка',
                'verbose_name_plural': 'Позиции подарка',
                'ordering': ['created_at'],
            },
        ),
    ]
