# Generated by Django 5.2.7 on 2026-03-02 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_stockmovement_reason_gift_giftitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена продажи'),
        ),
        migrations.AddField(
            model_name='gift',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда продан'),
        ),
        migrations.AddField(
            model_name='gift',
            name='sold_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gifts_sold', to=settings.AUTH_USER_MODEL, verbose_name='Кто продал'),
        ),
    ]
