# Generated by Django 5.2.7 on 2026-03-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_gift_sale_price_gift_sold_at_gift_sold_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftitem',
            name='line_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма'),
        ),
        migrations.AddField(
            model_name='giftitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за единицу'),
        ),
    ]
